# Why?

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

[source](https://numpy.org/devdocs/user/absolute_beginners.html)



To use numpy we first need to install it and then import it to our python script


## Install

There are two choices for installation, for conda users we can install numpy whith 

>conda install numpy

Or, if we don't use conda

>pip install numpy

## Import Numpy

As usual, after installing a library, we need to load it to be able to use it

In [1]:
import numpy as np

## Numpy Basics

Now, whenever we need to access a numpy function, we just call it by np.FUNCTIONNAME.

For example, to create a 1D array with 5, 7, 8 stored on it we just:

In [2]:
np.array([5,7,8])

array([5, 7, 8])

To create a sequence array we can use the function "arange"

In [3]:
seqArr01 = np.arange(start=5, stop=10)
print(seqArr01) 

[5 6 7 8 9]


Note that the first element of the array is 5
>start=5
but the last is the last value acceptable that is less than 10
>stop=10
In this case 
>9

or we can use steps of 2 

In [4]:
seqArr02 = np.arange(start=5, stop=20, step=2)
print(seqArr02) 

[ 5  7  9 11 13 15 17 19]


## Special Arrays

### zeros

In [5]:
zeroArr = np.zeros(5) # creates an array with 5 "zeros"
print(zeroArr)

[0. 0. 0. 0. 0.]


### Ones

In [6]:
onesArr = np.ones(3) # aray with 3 "ones"
print(onesArr)

[1. 1. 1.]


### Constant Arrays

In [7]:
eightArr = np.ones(10) * 8 # first creates a 10 ones array; and them multiplies all values by 8
eightArr

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

## Creating a matrix

A matrix can be thought as an array of arrays, so to create a matrix we just type ist values:

In [8]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

or we can reshap am 1D array into a 2D matrix

In [9]:
array1D = np.arange(9)
array1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
matrix2D = array1D.reshape(3,3)
matrix2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Special Functions

### random

In [11]:
np.random.rand(3) # 3 random numbers between 0 and 1

array([0.55635872, 0.42260894, 0.74383992])

In [12]:
np.random.randint(low=10,high=20,size=(10,10)) # 100 integers between 10 and 20 (excluding 20) stored in a matrix 10 by 10

array([[12, 18, 13, 11, 19, 17, 10, 15, 13, 16],
       [11, 12, 16, 13, 13, 17, 14, 17, 12, 11],
       [14, 12, 18, 16, 14, 18, 11, 14, 16, 10],
       [18, 18, 17, 16, 19, 17, 16, 13, 12, 13],
       [16, 16, 14, 13, 12, 10, 12, 11, 14, 12],
       [16, 15, 15, 10, 11, 13, 17, 13, 19, 17],
       [12, 10, 16, 14, 18, 16, 13, 15, 16, 19],
       [14, 12, 17, 10, 16, 19, 12, 14, 17, 18],
       [19, 15, 10, 19, 12, 13, 16, 15, 16, 14],
       [12, 11, 19, 12, 13, 19, 12, 16, 18, 11]])

In [13]:
np.random.randn(4) # 4 values from a standard normal distribution

array([ 0.24917572,  0.56923773, -1.86051709, -0.75640188])

### Linear spaced arrays

In [14]:
np.linspace(start=10,stop=20,num=100) # array with length = 100 with equally spaced values between 10 and 20 

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96

## Operations on arrays 

In [15]:
arr1 = np.arange(10)
arr2 = np.ones(10)*2
arr3 = arr1 + arr2
arr4 = arr1 / arr2
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## Statistics

In [16]:
# Mean
arr4.mean()

2.25

In [17]:
# Sum
arr4.sum()

22.5

In [18]:
# standard deviation
arr4.std()

1.4361406616345072

In [19]:
# min
arr4.min()

0.0

In [20]:
# max
arr4.max()

4.5

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3ec91331-1c3b-4ae6-9b0d-a4b8270f2efc' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>